training_data_paths:
- "data/train/training_corpus_kernel_synth_1m.arrow"
- "data/train/training_corpus_tsmixup_10m.arrow"
training_probability:
- 0.5
- 0.5
eval_data_paths:
- "data/val/training_corpus_kernel_synth_1m.arrow"
- "data/val/training_corpus_tsmixup_10m.arrow"
eval_probability:
- 0.5
- 0.5

context_length: 512
prediction_length: 64
min_past: 60
max_steps: 10_000 #200_000
save_steps: 10_000 #100_000
log_steps: 100
eval_steps: 1000
train_m: 2
eval_m: 64
per_device_train_batch_size: 128 #64
per_device_eval_batch_size: 16
learning_rate: 0.0001 #0.001
optim: adamw_torch_fused
num_samples: 20
shuffle_buffer_length: 100_000
gradient_accumulation_steps: 1
model_id: amazon/chronos-bolt-tiny
model_type: seq2seq
random_init: false #true
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: false #true TODO revert
lr_scheduler_type: cosine #linear
warmup_ratio: 0.1 #0.0
dataloader_num_workers: 1
max_missing_prop: 0.9
use_eos_token: true
