training_data_paths:
- "bigdata/train/kernelsynth/"
- "bigdata/train/tsmixup/"
training_probability:
- 0.1
- 0.9
eval_data_paths:
- "bigdata/val/kernelsynth/"
- "bigdata/val/tsmixup/"
eval_probability:
- 0.1
- 0.9

context_length: 512
prediction_length: 64
min_past: 60
max_steps: 200_000 #200_000
save_steps: 100_000
log_steps: 500
eval_steps: 5_000

# Engression bits
engression: true
train_m: 4
eval_m: 32
beta: 1.0
p: 2.0
lamb: 0.5
noise_dim: 8
seed: 42

per_device_train_batch_size: 32 #64
per_device_eval_batch_size: 16

# learning_rate: 0.0001 #0.001
lr_backbone: 1e-3 # 1e-5
lr_head: 5e-4

optim: adamw_torch_fused
num_samples: 20
shuffle_buffer_length: 100_000
gradient_accumulation_steps: 1
model_id: amazon/chronos-bolt-tiny # TODO
model_type: seq2seq
random_init: true # pretraining now! TODO
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: true #true TODO
lr_scheduler_type: linear #linear
warmup_ratio: 0.0 #0.0
dataloader_num_workers: 1
max_missing_prop: 0.9
use_eos_token: true
